---

#- name: restart web
#  systemd: name=mastodon-web state=restarted daemon_reload=yes
#  when: "'mastodon-web' in mroles"

#- name: restart streaming
#  systemd: name=mastodon-streaming state=restarted daemon_reload=yes
#  when: "'mastodon-streaming' in mroles"

#- name: restart sidekiq
#  systemd: name=mastodon-sidekiq state=restarted daemon_reload=yes
#  when: "'mastodon-sidekiq' in mroles"

- name: restart all
  systemd: name={{item}} state=restarted daemon_reload=yes
  when: "item in mroles_enabled"
  with_items:
  - "{{ mroles_all }}"
