---

- name: install requirements
  apt: name={{item}} state=latest
  with_items:
  - git
  - imagemagick
  - ffmpeg
  - libpq-dev
  - libxml2-dev
  - libxslt1-dev
  - nodejs
  - file
  - redis-tools
  - postgresql-contrib
  - build-essential
  - libreadline-dev
  - nfs-client

- name: install pgbouncer
  apt: name=pgbouncer state=latest
  when: pgbouncer_use

- name: npm
  npm: name={{item}} global=yes
  with_items:
  - yarn

- name: configure pgbouncer
  template: src=pgbouncer.ini dest=/etc/pgbouncer/pgbouncer.ini
  when: pgbouncer_use
  notify: reload pgbouncer

- name: configure pgbouncer users
  template: src=userlist.txt dest=/etc/pgbouncer/userlist.txt
  when: pgbouncer_use
  notify: reload pgbouncer

- name: enable pgbouncer
  lineinfile:
    dest: /etc/default/pgbouncer
    regexp: '^START='
    line: 'START=1'
  notify: start pgbouncer
  when: pgbouncer_use

- name: create mastodon user
  user:
    name: mastodon
    shell: /bin/bash

- name: install rbenv
  git:
    repo: https://github.com/rbenv/rbenv.git
    dest: /home/mastodon/.rbenv
  become: yes
  become_user: mastodon

- name: install ruby-build
  git: 
    repo: https://github.com/rbenv/ruby-build.git
    dest: /home/mastodon/.rbenv/plugins/ruby-build
  become: yes
  become_user: mastodon

- name: env stuff
  shell: "echo 'export PATH=\"$HOME/.rbenv/bin:$PATH\"' >> ~/.bash_profile"
  become: yes
  become_user: mastodon

- name: install ruby
  shell: /home/mastodon/.rbenv/bin/rbenv install -s 2.3.1
  become: yes
  become_user: mastodon

- name: rehash
  shell: /home/mastodon/.rbenv/bin/rbenv rehash
  become: yes
  become_user: mastodon

